name: Fetch SpaceX Jobs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  fetch-jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pup

      - name: Fetch SpaceX Careers Page
        run: curl -sSL "https://www.spacex.com/careers/jobs?search=software&location=bastrop%252C%2520tx" -o spacex_jobs.html

      - name: Extract Job Titles
        run: |
          cat spacex_jobs.html | pup 'h2 text{}' > job_titles.txt
          echo "Extracted job titles:"
          cat job_titles.txt

      - name: Comment on PR or Commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -s job_titles.txt ]; then
            COMMENT_BODY=$(echo -e "### SpaceX Job Titles Found:\n\n$(cat job_titles.txt | sed 's/^/- /')")
            gh api repos/${{ github.repository }}/issues/${{ github.event.number }}/comments -f body="$COMMENT_BODY"
          else
            echo "No job titles found."
          fi
